repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: pretty-format-json
        args: ['--autofix']
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.0
    hooks:
      - id: trufflehog
  - repo: local
    hooks:
      - id: run-make-fmt
        name: Run make fmt
        entry: make fmt
        language: system
        pass_filenames: false
      - id: run-make-build
        name: Run make build
        entry: make build
        language: system
        pass_filenames: false
      - id: run-make-lint
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: run-make-test
        name: Run make test
        entry: make test
        language: system
        pass_filenames: false
